# Commented lines that are ignored start with the '#' mark.
# # A helpful tutorial for more information on make
# # https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all : bst_tests.c my_bst.c
	gcc -Wall -g -o tests bst_tests.c my_bst.c

clean :
	rm tests
